stages:
    - build
    - test
    - run

build:linux:
    image: node:8
    stage: build
    script: 
        - npm install
        - npm run build
    artifacts:
        paths:
            - dist/
            - node_modules/
            - resources/
            - src/
            - test/
            - package.json
            - tsconfig.build.json
            - tsconfig.json

# build:windows:
#     image: mcr.microsoft.com/windows/servercore:ltsc2019
#     stage: build
#     script:
#         - bin\install-nodejs.cmd
#         - bin\refreshenv.cmd
#         - npm install
#         - npm run build
#     artifacts:
#         paths:
#             - dist/
#             - node_modules/
#             - resources/
#             - src/
#             - test/
#             - package.json
#             - tsconfig.build.json
#             - tsconfig.json        

test:linux:
    image: node:8
    stage: test
    script: npm test
    dependencies:
      - build:linux

# test:windows:
#     stage: test
#     script: npm test
#     artifacts:
#         paths:
#             - coverage/
#     dependencies:
#       - build:windows

run:linux:
    image: node:8
    stage: run
    script: npm start path
    dependencies:
      - test:linux

# run:windows:
#     stage: run
#     script: npm start path
#     dependencies:
#       - test:windows